#!/bin/bash

find_current_user() {
  local user="$(git remote -v | head -1 | awk '{print $2}' | tr -s ':' | cut -d ':' -f 1 | tr -s '@' | cut -d '@' -f 2)"
  
  if [[ "$user" = "github.com" ]]; then
    user="globar"
  fi
  echo "$user"
}

print_user_list() {
  local hosts=$(cat ~/.ssh/config| grep 'Host ' | awk '{print $2}')
  printf "global"
  if [[ "global" = "$CURRENT_USER" ]]; then
    printf "[*]\n"
  else
    printf "[ ]\n"
  fi;  
  for host in $hosts; do 
    if [[ "$(ssh -G $host | grep user | awk '{print $2}' | head -n 1)" = "git" ]]; then
      printf "$host"
      
      if [[ "$host" = "$CURRENT_USER" ]]; then
        printf "[*]\n"
      else
        printf "[ ]\n"
      fi;
    fi; 	
  done
}

create_info() {
  while : ; do
    printf "email > " 
    read email

    if [[ -z "$email" ]]; then
      printf '%s\n' "email is required!"
      continue
    else
      break;
    fi
  done
  
  while : ; do
    printf "name > "
    read name

    if [[ -z "$name" ]]; then
      printf '%s\n' "name is required!"
      continue
    else
      break;
    fi
  done

  echo "\nCreate Public Key...\n"
  ssh-keygen -t rsa -C "$email" -f ~/.ssh/id_rsa_gitzua_$name
  write_ssh_config $email $name
}

write_ssh_config() {
  local email="$1"
  local name="$2"
  identityFile=~"/.ssh/id_rsa_gitzua_$name"

  cat >> ~/.ssh/config <<EOF

###########################
##Generated By GITZUAAA~!##
###########################
#gitzua-$name-email $email
Host $name
  HostName github.com
  User git
  IdentityFile $identityFile
EOF
}

change_user() {
  local changeUser="$1"
  local changeUserEmail=$(cat ~/.ssh/config | grep gitzua-$1-email | awk '{printf $2}')
  local currentRepository=$(git remote -v | head -1 | awk '{print $2}' | tr -s ':' | cut -d ':' -f 2)
  git remote set-url origin git@$changeUser:$currentRepository
  git config --local user.name $changeUser
  git config --local user.email $changeUserEmail
  CURRENT_USER=$(find_current_user)
}

check_use_git() {
  if [[ -d .git ]]; then
    printf ""
  else
    echo "Not a git repogitory"
    exit 1   
  fi
}

check_git_url_support() {
  if [[ $1 != git@* ]]; then
    echo "not supported path. supported only ssh type."
    exit 1;
  fi
}

################################
############ GITZUA ############
################################

which git &> /dev/null
if [ "$?" != "0" ]; then
    echo "git is not installed..."
    exit 1
fi

check_use_git

check_git_url_support $(git remote -v | head -n 1 | awk '{print $2}')

#if [[ -n "$(git remote -v | grep https)" ]]; then
#  echo "not supported https version. please, change ssh version."
#  exit 1;
#fi

CURRENT_USER=$(find_current_user)

if [[ -z "$CURRENT_USER" ]]; then
    exit 1;
fi

print_user_list
#change_user $1
#create_info
